### PR TITLE
[ Main-Group-19 ] Main group 19 Eduardo-Nikolai-Antônio-Vitor

### PR DESCRIPTION
**Pull request by EduardoPrando**
XABLAU - XABLI - XABLOU

### CODE REVIEW

**Review by Vitor-Hugo-Dev — APPROVED** [review]
top

**Review by Raikouve — APPROVED** [review]
Show de bola

**Review by eaeniko — APPROVED** [review]
Parabensss 😎 🙏

**Comment by EduardoPrando** [comment]
requirement 01 and 02

**Pull request merged**
